apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-named-conf
stringData:
  named.conf: |
    // use the user-provided named.conf.options
    include "/named_config/named.conf.options";
    // use the default files
    include "/etc/bind/named.conf.local";
    include "/etc/bind/zones.rfc1918";
    include "/etc/bind/named.conf.default-zones";
