apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-named-conf
stringData:
  named.conf: |
    options {
      directory "/var/cache/bind";

      dnssec-validation yes;
      listen-on port 53 { any; };
      recursion yes;
      allow-query { any; };

      {{ if .Values.resolver.enabled -}}
      forwarders {
      {{- range .Values.resolver.forwarders }}
        {{ . }};
      {{- end }}
      };
      {{- end }}

    };
    // use the default zones
    include "/etc/bind/named.conf.default-zones";
