apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-named-conf
stringData:
  named.conf: |
    options {
      directory "/var/cache/bind";

      {{ if .Values.resolver.dnssec_validation -}}
      dnssec-validation yes;
      {{- else -}}
      dnssec-validation no;
      {{- end }}
      listen-on port 5053 { any; };
      {{ if .Values.resolver.ipv6_enabled -}}
      listen-on-v6 5053 { any; };
      {{- else -}}
      listen-on-v6 { none; };
      {{- end }}
      recursion yes;
      allow-query { any; };

      {{ if .Values.resolver.enabled -}}
      forwarders {
      {{- range .Values.resolver.forwarders }}
        {{ . }};
      {{- end }}
      };
      {{- end }}

    };
    // use the default zones
    include "/etc/bind/named.conf.default-zones";
